In [1]:
import tensorflow as tf
from osgeo import gdal
import matplotlib.pyplot as plt
from PIL import Image
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
import matplotlib.colors as clr

ds=gdal.Open('images amersfoort/triplesat_20180418_amersfoort.tif')

In [2]:
R = ds.GetRasterBand(1).ReadAsArray()
G = ds.GetRasterBand(2).ReadAsArray()
B = ds.GetRasterBand(3).ReadAsArray()

In [15]:
NIR = ds.GetRasterBand(4).ReadAsArray()

In [3]:
print(R)
print(G)
print(B)
# print(NIR)

[[1220 1118  914 ...  626  635  646]
 [1222 1195 1030 ...  675  638  652]
 [1148 1245 1102 ...  673  645  682]
 ...
 [ 878  841  847 ...  763  762  767]
 [ 865  869  860 ...  785  763  787]
 [ 834  827  818 ...  793  779  801]]
[[1196 1073  816 ...  472  479  489]
 [1192 1152  946 ...  526  479  493]
 [1098 1199 1021 ...  520  484  526]
 ...
 [ 683  640  647 ...  589  585  586]
 [ 666  669  659 ...  614  584  605]
 [ 627  616  606 ...  620  597  615]]
[[1166  978  667 ...  267  274  286]
 [1156 1074  822 ...  329  274  290]
 [1042 1132  916 ...  321  278  328]
 ...
 [ 497  444  451 ...  492  486  487]
 [ 477  482  466 ...  520  482  507]
 [ 430  418  401 ...  526  497  518]]


In [ ]:
row = range(len(R))
column = range(len(R[0]))

rgb = []
for i in row:
    if i % 100 == 0:
        print(i)
    rgb_row = []
    for j in column:
        rgb_row.append([(R[i][j]), (G[i][j]), (B[i][j])])
        
    rgb.append(rgb_row)
        
rgb = np.array(rgb)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600


In [ ]:
file = open('rgb.txt','w')
file.write(rgb)
file.close()

In [34]:
print(rgb.shape)

# plt.imshow(rgb)
# plt.show()

# rgb_map = Image.fromarray(rgb, 'RGB')
# rgb_map.save('rgb_map.tif')

(0,)


In [ ]:
rgb_map = Image.fromarray(NIR, 'RGB')
rgb_map.save('NIR_map.tif')